version: 2.1

jobs:
  analyze:
    docker:
      - image: rwspeight/dotnet-sonar-scanner
    steps:
      - checkout
      - run:
          name: Run Code Analysis
          command: |
            scan.sh \
              ${SONAR_PROJECT_KEY} \
              ${SONAR_ORGANIZATION} \
              ${SONAR_AUTH_TOKEN} \
              tests.dll \
              ./src 
workflows:
  main:
    jobs:
      - analyze:
          context: SonarCloud
