version: 2.1

jobs:
  analyze:
    docker:
      - image: rwspeight/dotnet-sonar-scanner
    steps:
      - checkout
      - run:
          name: Run Code Analysis
          command: |
            scan.sh \
              rwspeight_SonarCloudPoco \
              badger-works \
              ${SONAR_AUTH_} \
              ./src/tests/bin/Release/netcoreapp3.1/tests.dll \
              ./src 
workflows:
  main:
    jobs:
      - analyze:
          context: SonarCloud
